Bin: Simplify neovim update

diff --git a/bin/install_dotfiles b/bin/install_dotfiles
--- a/bin/install_dotfiles
+++ b/bin/install_dotfiles
@@ -77,22 +77,11 @@ echo
 
 echo "Updating neovim"
 echo "---------------"
-set -l nvim_update nvim +PlugInstall +qall
-if not eval $nvim_update > /dev/null ^ /dev/null
-    echo "Trying with expect"
-    set -l expect_script "\
-    log_user 0
-    spawn $nvim_update
-    expect 'Press ENTER or type command to continue'
-    send '\n'
-    interact
-    "
-    if not expect -c "$expect_script" > /dev/null ^ /dev/null
-        set_color red
-        echo "That failed terribly"
-        set_color normal
-        exit 1
-    end
+if not nvim +"PlugInstall --sync" +qa
+    set_color red
+    echo "That failed terribly"
+    set_color normal
+    exit 1
 end
 set_color green
 echo "All good!"
