Bin: Make lock-screen fancy

diff --git a/bin/lock-screen b/bin/lock-screen
--- a/bin/lock-screen
+++ b/bin/lock-screen
@@ -1,7 +1,7 @@
 #!/bin/bash
 set -e
 
-output_file=$(mktemp).png
+output_file="$(mktemp).png"
 
 if [ -z "$1" ]
 then
@@ -10,16 +10,30 @@ else
     message="$1"
 fi
 
-convert \
-    -size 600x400 xc:white \
+if ! font="$(fc-match sans file | cut -d= -f2)"
+then
+    echo "Couldn't find font"
+    font=""
+fi
+
+if ! convert \
+    -font "$font" \
+    -size 1024x768 xc:white \
     -gravity center \
     -pointsize 24 \
     -fill black \
     -annotate +0+0 \
     "$message" \
     "$output_file"
-swaylock \
-    --show-failed-attempts \
-    --color ff6e67 \
-    --daemonize \
-    --image "$output_file"
+then
+    swaylock \
+        --show-failed-attempts \
+        --color ff6e67 \
+        --daemonize
+else
+    swaylock \
+        --show-failed-attempts \
+        --color ff6e67 \
+        --daemonize \
+        --image "$output_file"
+fi
